//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NwsAlerts.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NwsAlertApi.MessageTypes MessageTypes {
            get {
                return ((global::NwsAlertApi.MessageTypes)(this["MessageTypes"]));
            }
            set {
                this["MessageTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Severe Thunderstorm Watch\r\nTornado Watch\r\nTornado Warning\r\nFlood Advisory\r\nFlood " +
            "Watch\r\nFlood Warning\r\nFlash Flood Watch\r\nFlash Flood Warning\r\nSmall Stream Flood" +
            " Advisory\r\nUrban And Small Stream Flood Advisory")]
        public string EventList {
            get {
                return ((string)(this["EventList"]));
            }
            set {
                this["EventList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::NwsAlertApi.Severities Severity {
            get {
                return ((global::NwsAlertApi.Severities)(this["Severity"]));
            }
            set {
                this["Severity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\visua\\OneDrive\\Documents\\Streaming\\Weather")]
        public string OutputFolder {
            get {
                return ((string)(this["OutputFolder"]));
            }
            set {
                this["OutputFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\visua\\OneDrive\\Documents\\Streaming\\Weather\\")]
        public string WarningOutputPath {
            get {
                return ((string)(this["WarningOutputPath"]));
            }
            set {
                this["WarningOutputPath"] = value;
            }
        }
    }
}
