/* 
 * weather.gov API
 *
 * weather.gov API
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AnyOfsize
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AnyOfsizeTests
    {
        // TODO uncomment below to declare an instance variable for AnyOfsize
        //private AnyOfsize instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AnyOfsize
            //instance = new AnyOfsize();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AnyOfsize
        /// </summary>
        [Test]
        public void AnyOfsizeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AnyOfsize
            //Assert.IsInstanceOfType<AnyOfsize> (instance, "variable 'instance' is a AnyOfsize");
        }



    }

}
